server:
  port: 8084 #运行端口号
spring:
  application:
    name: gateway #服务名称
  main:
    web-application-type: reactive
  redis:
    host: localhost
    port: 6379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true  #通过地址访问服务
          lower-case-service-id: true
      globalcors: #全局跨域配置
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            exposedHeaders:
              - content-type
            allowedHeaders:
              - content-type
            allowCredentials: true
            allowedMethods:
                - GET
                - OPTIONS
                - PUT
                - DELETE
                - POST
      routes:
        - id: fuse_route
          uri: lb://mysql-service
          predicates:
              - Method=GET
          filters:
            - PrefixPath=/file/test
      default-filters:
        - name: Hystrix
          args:
            name: fallbackCmd  # 指定hystrix command的名称
            fallbackUri: forward:/fallback  # 注意fallbackUri要以forward开头
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 3
            key-resolver: "#{@uriKeyResolver}"


hystrix.command.fallbackCmd.execution.isolation.thread.timeoutInMilliseconds: 5000



eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://root:root@localhost:8001/eureka/ #配置注册中心地址

