server:
  #  port: 9411
  compression:
    # 是否开启压缩 默认false
    enabled: true
spring:
  application:
    name: zipkin-server
  main:
    # 让应用以非web服务方式启动 server.port配置将会失效
    web-application-type: none
armeria:
  ports[0]:
    ip: 127.0.0.1
    port: 9411
    protocol: HTTP